### ISSUE TITLE
No commands available or listed.

### ISSUE THREAD

**Issue by adiba** [directus/cli#12]
Note: I am running this on Windows.

Firstly, after installation, I get warnings about 2 vulnerabilities:
```
npm WARN deprecated @types/pino@7.0.5: This is a stub types definition. pino provides its own type definitions, so you do not need this installed.
npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 412 packages, and audited 413 packages in 1m

42 packages are looking for funding
  run `npm fund` for details

2 critical severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
Then, when I try to run a command using `npx directusctl instance connect`:

```
 ERROR 
  Unknown command: "directusctl instance connect"
```

When I run `--help`, no commands are listed:

```
 SYNOPSIS 

  directusctl <command> [options]

 COMMANDS 
  These are all the commands you can use to manage your project or
  installation


 OPTIONS 

  --help  boolean  Show help for the specified command
```

Thank you!

**Comment by rlora** [comment]
Hello,

I'm experiencing the same in MacOS. Haven't use the CLI before so I don't have a past reference on how it should work. But it seems that the commands are missing.

![Screen Shot 2022-08-22 at 9 02 01 PM](https://user-images.githubusercontent.com/1533339/186045688-a16b0c0e-a00b-4f86-90cf-2efff94087dc.png)

**Comment by moritzgvt** [comment]
Same here on Mac. 

For me the last stable version is ```@directus/cli@9.12.0```. 

After this the package is throwing an ```SyntaxError: Unexpected token 'const'``` as mentioned in this issue https://github.com/directus/cli/issues/1.

**Comment by maylukas** [comment]
Same problem with Directus CLI 9.14.2 on Mac OS

**Comment by badrange** [comment]
I also have the same issue on Linux. I added the cli to the repository like this: 

`npm install @directus/cli`

And get the same error when I try to run the cli like this: `  Unknown command: "directusctl instance"`
and with npx: `npx directusctl instance connect`

>   Unknown command: "directusctl instance"

**Comment by lorenzogrv** [comment]
Same problem here, Linux Host, `@directus/cli@9.14.2`

It doesn't find commands globally installed neither locally installed within a project

I can help diagnosing with more information if needed.
